version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image and push to registry
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            make all IP2LOCATION_TOKEN=$IP2LOCATION_TOKEN

workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # Every week
          filters:
            branches:
              only:
                - master
    jobs:
      - build
